"""Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(nmax=4e6):
    prev = 1
    curr = 2

    currsum = 2
    while curr <= nmax:
        temp = curr
        curr += prev
        prev = temp

        if not curr % 2:
            currsum +=curr

    return currsum
