"""
How many distinct terms are in the sequence generated by ab for 2 <= a
<= 100 and 2 <= b <= 100?
"""
def pows(maxa, maxb):
    for a in range(2, maxa+1):
        for b in range(2, maxb+1):
            yield a**b


def p29():
    return len(set(pows(100, 100)))
