"""
Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:

Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ...
Pentagonal Pn=n(3n-1)/2 1, 5, 12, 22, 35, ...
Hexagonal Hn=n(2n-1) 1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from utils import (triangle,
                   pentagonal,
                   hexagonal)


def all_three():
    n, m, k = 285, 165, 143
    while True:
        if triangle(n) == pentagonal(m) == hexagonal(k):
            yield triangle(n)

        k += 1
        n += 2
        while pentagonal(m) < hexagonal(k):
            m += 1


def p45():
    from itertools import islice
    return list(islice(all_three(), 2))[-1]
